### ISSUE TITLE
Missing become: true during packages install makes this role unusable in other playbooks

### ISSUE THREAD

**Issue by iirekm** [robertdebock/ansible-role-molecule#1]
**Describe the bug**

**To Reproduce**
1. Run this role:
2. See error

**Expected behavior**

**Error**
Please show the resulting error. If applicable a snippet of the playbook including the role ran with `-vvv`

**Environment**
- Control node OS: [e.g. Debian 9]
- Control node Ansible version: [e.g. 2.6.2]
- Managed node OS: [e.g. CentOS 7]

**Additional context**

**Comment by robertdebock** [comment]
Thanks for you feedback, I think I understand what you mean and write a fix for it.

**Comment by robertdebock** [comment]
Be aware that the role is not release on Galaxy, that may take a day or two as I'm in the middle of a massive commit/test.

**Comment by robertdebock** [comment]
This has been fixed, sorry for not updating the issue earlier!
